## Coding Exercise #0102

### 1. NumPy array operations:

#### 1.1. '+' and '*' operators for Python lists:

In [2]:
import numpy as np

In [20]:
a = [1, 2, 3]

In [21]:
a + a

[1, 2, 3, 1, 2, 3]

In [22]:
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [23]:
b = np.array([1, 2, 3])

In [24]:
b*3

array([3, 6, 9])

In [25]:
b + b

array([2, 4, 6])

In [26]:
np.repeat(b, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

#### 1.2. '+' and '*' operators for NumPy arrays:

In [27]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [28]:
a+b

array([5, 7, 9])

In [29]:
a-b

array([-3, -3, -3])

In [30]:
a*b

array([ 4, 10, 18])

In [31]:
a/b

array([0.25, 0.4 , 0.5 ])

1.2.2 Broadcating

In [32]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

# add the arrays together
c = a + b

print(c)

[11 22 33]


In [33]:
# create a 2D array
a = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])

# add the arrays together
c = a + b

print(c)

[[11 22]
 [13 24]]


In [34]:
# a = np.array([1, 2, 3])
# b = np.array([[1, 2], [3, 4]])

# c = a + b  # raises ValueError: operands could not be broadcast together with shapes (3,) (2,2

In [69]:
a = np.array([1, 2, 3])
b = np.array([1.5, 2.5, 3.5])

c = a + b  # raises TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('int64') dtype('float64')

In [36]:
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])

c = a + b  # raises ValueError: operands could not be broadcast together with shapes (3,) (3,1)

#### 1.3. Universal functions:

In [37]:
x = np.array([0, 1, 2, 3, 4, 5])

In [38]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [39]:
np.exp(x)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [40]:
type(np.sqrt)

numpy.ufunc

In [41]:
type(np.exp)

numpy.ufunc

#### 1.4. NumPy functions:

In [71]:
np.random.seed(123)
a = np.random.randint(1, 11, size=1000)

In [43]:
np.unique(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
np.median(a)

5.0

In [45]:
np.sum(a)

5485

In [46]:
np.round(np.var(a),2)

8.19

In [47]:
np.round(np.mean(a),2)

5.48

In [48]:
np.round(np.std(a),2)

2.86

In [49]:
np.max(a)

10

In [50]:
np.min(a)

1

#### 1.5. Statistical methods of NumPy arrays:

In [72]:
x=np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
x.sum()

55

In [53]:
x.mean()

5.5

In [54]:
x.std()

2.8722813232690143

In [55]:
x.var()

8.25

In [56]:
x.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [57]:
y = np.arange(1,10)
y = y.reshape((3,-1))
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [58]:
print(y.mean(axis=0))

[4. 5. 6.]


In [59]:
print(y.mean(axis=1))

[2. 5. 8.]


In [3]:
z = np.random.randint(10,size=1000)

In [4]:
z.max()

9

In [62]:
z.min()

0

In [5]:
(z > 5).sum()

395

In [64]:
np.unique(z)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
sorted(set(z))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [66]:
a = np.array([2,-3,4,5,7,0,1,-1])

In [67]:
a.argmax()

4

In [68]:
a.argmin()

1