Array Transposition

In [2]:
import numpy as np

In [ ]:
arr=np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [4]:
arr=np.random.randn(6,3)
arr

array([[ 0.3254361 ,  0.81161471, -0.01068979],
       [ 1.21719519, -1.77634668, -0.47080553],
       [-0.64614721,  0.96974886, -0.82679407],
       [-0.11890945, -0.65011411,  0.82337767],
       [-1.05296174,  0.77857672, -0.03500212],
       [-1.24604846,  1.18223807, -0.66024135]])

In [5]:
np.dot(arr.T, arr)

array([[ 4.68048365, -4.74026515,  0.71933084],
       [-4.74026515,  7.18105574, -1.31724848],
       [ 0.71933084, -1.31724848,  2.02045513]])

In [6]:
arr=np.arange(16).reshape(2,2,4)

In [7]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [8]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [9]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [10]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])