In [2]:
import numpy as np

2

In [3]:
# implement sigmoid function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

arr = np.array([1, 2, 3, 4, 5])
print(sigmoid(arr))

[0.73105858 0.88079708 0.95257413 0.98201379 0.99330715]


3

In [4]:
zero = np.zeros(10)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4

In [5]:
print(zero.size)
print(zero.itemsize)
#How to find the memory size of any array
print("memory size: ", zero.size * zero.itemsize)

10
8
memory size:  80


5

In [6]:
arr = np.zeros(10)
arr[4] = 1
arr


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7

In [7]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8

In [8]:
arr = np.arange(0,10)
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

9

In [9]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10

In [10]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

11

In [11]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12

In [12]:
#Create a 3x3x3 array with random values
np.random.random((3,3,3))

array([[[0.83232165, 0.11986357, 0.66674473],
        [0.2707906 , 0.03303994, 0.23383202],
        [0.15463033, 0.04073053, 0.55320103]],

       [[0.54417855, 0.42870721, 0.01833164],
        [0.07432631, 0.65348942, 0.26117125],
        [0.31604239, 0.76484758, 0.86530421]],

       [[0.35187724, 0.43387707, 0.89192995],
        [0.73400501, 0.60462239, 0.53074832],
        [0.07965068, 0.88257371, 0.39156806]]])

13

In [13]:
arr = np.random.random((10,10))
print(arr.min())
print(arr.max())

0.010280146505150745
0.9997840355994287


14

In [14]:
arr = np.random.random(30)
arr.mean()

0.5094906253750958

15

In [15]:
arr = np.ones((10,10))
arr[1:-1,1:-1] = 0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

16

In [16]:
arr = np.ones((5,5))
np.pad(arr, pad_width=1, mode='constant', constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

17

In [17]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

18

In [18]:
arr = np.diag(1+np.arange(4), k=-1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

20

In [19]:
# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
np.unravel_index(99, (6,7,8))

(1, 5, 3)

22

In [20]:
arr = np.random.random((3,3))
arr = (arr - np.mean(arr)) / (np.std(arr))
arr

array([[-0.81601435, -0.59681417, -1.31682653],
       [ 1.01780118,  1.01296752,  0.21957463],
       [-1.47848722,  0.85389328,  1.10390565]])

23

In [21]:
# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color = np.dtype([("r", np.ubyte, 1),
                    ("g", np.ubyte, 1),
                    ("b", np.ubyte, 1),
                    ("a", np.ubyte, 1)])

C:\Users\user\AppData\Local\Temp\ipykernel_11636\3671468597.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


24

In [22]:
# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
np.dot(np.ones((5,3)), np.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

25

In [23]:
# 25. Given a 1D array, negate all elements which are between 3 and 8, in place.
arr = np.arange(11)
arr[(3 < arr) & (arr <= 8)] *= -1
arr

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

29

In [24]:
# 29 How to round away from zero a float array ?
arr = np.random.uniform(-10,+10,10)
np.copysign(np.ceil(np.abs(arr)), arr)

array([10.,  1., -6.,  6.,  1., -7.,  6., -2.,  2.,  1.])

30

In [25]:

# 30 How to find common values between two arrays?
arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10,10)
np.intersect1d(arr1, arr2)


array([0, 4, 7, 8, 9])

31

In [26]:

# 31 How to ignore all numpy warnings (not recommended)?
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

33

In [27]:
print("yestedray" ,np.datetime64('today') - np.timedelta64(1, 'D'))
print("today", np.datetime64('today'))
print("tomorrow", np.datetime64('today') + np.timedelta64(1, 'D'))

yestedray 2023-04-29
today 2023-04-30
tomorrow 2023-05-01


34

In [28]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

35

In [32]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

36

In [33]:
arr = np.random.uniform(0,10,10)
print(arr - arr%1)
print(np.floor(arr))
print(np.ceil(arr) - 1)
print(arr.astype(int))
print(np.trunc(arr))

[8. 7. 1. 7. 6. 0. 6. 0. 0. 1.]
[8. 7. 1. 7. 6. 0. 6. 0. 0. 1.]
[8. 7. 1. 7. 6. 0. 6. 0. 0. 1.]
[8 7 1 7 6 0 6 0 0 1]
[8. 7. 1. 7. 6. 0. 6. 0. 0. 1.]


37

In [35]:
arr = np.zeros((5,5))
arr += np.arange(5) 
arr

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

39

In [41]:
arr = np.linspace(0,1,11)
arr

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

40

In [48]:
arr = np.random.random(10)
arr.sort()
arr

array([0.03416607, 0.07235498, 0.11382731, 0.19191192, 0.20907646,
       0.31033329, 0.53937395, 0.63931167, 0.80164795, 0.97187658])

41

In [50]:
arr = np.ones(5)
np.add.reduce(arr)

5.0

42

In [52]:
A = np.random.random(10)
B = np.random.random(10)
print(np.allclose(A,B))
print(np.array_equal(A,B))


False
False
